"""
build-help.py
Reads all markdown files from help/ folder and generates js/help-content.js
Usage: python help/build-help.py
"""

import os
import json
from pathlib import Path

def escape_js_string(text):
    """Escape text for JavaScript template literal"""
    # Use JSON encoding which handles most escaping, then adjust for template literals
    return text.replace('\\', '\\\\').replace('`', '\\`').replace('${', '\\${')

def build_help_content():
    """Build help-content.js from all .md files in help/ folder"""

    help_dir = Path('help')
    output_file = Path('js/help-content.js')

    if not help_dir.exists():
        print(f"Error: {help_dir} directory not found")
        return False

    # Collect all markdown files
    help_files = {}
    md_files = sorted(help_dir.glob('*.md'))

    if not md_files:
        print(f"Warning: No .md files found in {help_dir}")
        return False

    for md_file in md_files:
        # Use filename without extension as key
        key = md_file.stem
        content = md_file.read_text(encoding='utf-8')
        help_files[key] = escape_js_string(content)
        print(f"  Added: {md_file.name} -> '{key}'")

    # Generate JavaScript file
    js_content = """/**
 * help-content.js
 * Auto-generated help content from markdown files
 * DO NOT EDIT THIS FILE DIRECTLY - Edit .md files in help/ folder and run build-help.py
 */

const HelpContent = {
"""

    for key, content in help_files.items():
        js_content += f"    '{key}': `{content}`,\n\n"

    js_content += "};\n"

    # Write output file
    output_file.write_text(js_content, encoding='utf-8')
    print(f"\nGenerated: {output_file}")
    print(f"Total help topics: {len(help_files)}")

    return True

if __name__ == '__main__':
    print("Building help content...")
    success = build_help_content()
    if success:
        print("Done!")
    else:
        print("Build failed!")
        exit(1)
