site_name: Astryx Help
site_description: Help documentation for Astryx astrophotography planning
docs_dir: docs
site_dir: site
use_directory_urls: false

theme:
  name: material
  logo: logo-wo-ring.png
  favicon: logo-wo-ring.png
  font: false
  palette:
    scheme: slate
    primary: black
    accent: deep purple
  features:
    - navigation.instant
    - navigation.top
    - navigation.expand
    - navigation.footer
    - toc.integrate
    - toc.follow
    - search.highlight
    - search.suggest
    - content.code.copy
    - content.tabs.link
    - content.tooltips
    - navigation.sections
    - navigation.indexes

nav:
  - Home: index.md
  - Best Month Calculation: best-months.md
  - Yearly Observability: yearly-observability.md
  - Target Database: target-database.md
  - Change Log: changelog.md

markdown_extensions:
  - tables
  - toc:
      permalink: true
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.snippets
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.critic
  - pymdownx.arithmatex

extra_javascript:
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - stylesheets/extra.css

plugins:
  - search:
      lang: en
      separator: '[\s\-]+'
  - offline
  - awesome-pages
  - glightbox
